### ISSUE TITLE
Double Integrator example not working with fixed time

### ISSUE THREAD

**Issue by karthyyy** [grampc/pygrampc#6]
Hi,

   I was modifying Double Integrator example in PYGRAMPC and observed the following.

1) With OptimTIme = "On", the code is simulating correctly with states reached at around 3.5 sec.
2) With OptimTIme = "Off" in 'json' file, following error is shown,

```
Traceback (most recent call last):
  File "...\examples\DoubleIntegrator\DoubleIntegrator.py", line 69, in <module>
    if i + 1 > len(vec.t) or vec.t[i + 1] > Tsim:
IndexError: index 8001 is out of bounds for axis 0 with size 8001
```
 
 So I changed " `if i + 1 > len(vec.t) or vec.t[i + 1] > Tsim:`"  to " `if i + 1 > len(vec.t) or vec.t[i] > Tsim:`" there is no simulation error but states are not reached to the desired values even after 8 sec. In the software manual example, for fixed time problem, the states are converged within 4sec.

![image](https://github.com/user-attachments/assets/c8b990f6-535e-4da0-9eec-e326b8b04cfd)

![image](https://github.com/user-attachments/assets/b0cbb284-53cf-4d97-bbc2-87a69fe7deae)
 

The JSON file content is as follows
 ```
{
  "Parameters":
  {
    "x0": [-1.0, -1.0],
    "xdes": [0.0, 0.0],
    "u0": [0.0],
    "udes": [0.0],
    "umax": [1.0],
    "umin": [-1.0],
    "Thor": 5.25,
    "Tmax": 10.0,
    "Tmin": 1.0,
    "dt": 0.01,
    "t0": 0.0
  },
  "Options":
  {
    "OptimTime": "off",
    "Nhor": 50,
    "OptimTimeLineSearchFactor": 0.35,
    "ConstraintsAbsTol": [1e-3, 1e-3]
  }
}
```
 
  Can someone please help to see whether I am missing any settings ?

Thanks n Regards,
       Karthik

**Comment by ThoreWietzke** [comment]
The index error you mentioned is indeed an error in the example.

When ´OptimTime´ is off, the example behaves like expected. GRAMPC does try to find a trade-off between the control and the setpoint specified by ´udes´.

Did I miss something @avoelz ?

**Comment by karthyyy** [comment]
@ThoreWietzke,

   Thanks for the reply. In that case, can I put the state error (x-xdes) in the cost function rather than putting it as Terminal constraint (or along with Terminal Constraint) ?

Regards
  Karthik

**Comment by ThoreWietzke** [comment]
That would help the MPC to steer x to the desired state

**Comment by karthyyy** [comment]
Hi @ThoreWietzke ,

  Thanks for the response. I did the following modifications and now the states are converged but at around 8 seconds. Also, on deeper thought, I think its not what I require. By considering error term in the integral function, the problem changes to unconstrained optimization (with respect to desired state value) and there is no guarantee that my unspecified boundary constraint is met. Please correct if wrong

```
    # def lfct(self, out, t, x, u, p, xdes, udes):
    #     out[0] = self.CostIntegral * (u[0] - udes[0]) ** 2

    # def dldu(self, out, t, x, u, p, xdes, udes):
    #     out[0] = 2 * self.CostIntegral * (u[0] - udes[0])

    def lfct(self, out, t, x, u, p, xdes, udes):
        out[0] = self.CostIntegral * (x[0] - xdes[0]) ** 2   # Only first state variable is used for optimization

    def dldx(self, out, t, x, u, p, xdes, udes):
        out[0] = 2 * self.CostIntegral * (x[0] - xdes[0])
```

   In addition, while going through GRAMPC C implementation, `const char* OptimTime = "off"; `and it still uses control efforts for optimization as `"out[0] = pCost[0] * POW2(u[0] - udes[0]);"` . While running the file "main_OCP_DOUBLE_INTEGRATOR.c", its generating correct results (states converged and time is 5.25) in the text files.

Regards,
     Karthik R

**Comment by ThoreWietzke** [comment]
Oh, you look at two completely different examples.

The example here in pygrampc is for the MPC example, not the OCP you are looking at.
You should look at `main_DOUBLE_INTEGRATOR.c`

**Comment by karthyyy** [comment]
HI @ThoreWietzke ,

  Thanks for the reply. Sorry I am still confused. As mentioned above, 

> Also, on deeper thought, I think its not what I require. By considering error term in the integral function, the problem changes to unconstrained optimization (with respect to desired state value) and there is no guarantee that my unspecified boundary constraint is met. Please correct if wrong

As per your advice, 

1) I executed the program "main_DOUBLE_INTEGRATOR.c", it converged must faster at 3.45700 seconds.
2) I executed the python program with option `"ShiftControl": "off"`, &` "OptimTime": "off",` to simulate the conditions of `main_OCP_DOUBLE_INTEGRATOR.c`, still there is no change in waveforms.

My objective is to solve the double integrator problem as an OCP with a) desired state values as boundary conditions b) u-udes in the cost function and c) fixed time.

Whether I am making any fundamental mistakes ?

Regards
  Karthik

**Comment by ThoreWietzke** [comment]
Then I propose, that you look into the corresponding probfct_OCP.c file and copy the implementation accordingly to python. Then you should also make sure, that all settings for GRAMPC are matching, e.g. MaxGradIter and MaxMultIter.

And you don't have to ping me in every post ;)

**Comment by karthyyy** [comment]
Hi @ThoreWietzke ,
  
  Thanks for the response. I followed your advice. The modified file is attached herewith (plz change extension from .txt to .py). However since I couldn't find help files for PYGRAMPC, the code is throwing errors at functions like  `convergence_test_gradient`, `convergence_test_constraints`, `grampc_printstatus`.

[DoubleIntegrator.txt](https://github.com/user-attachments/files/17720858/DoubleIntegrator.txt)

 
  Can you please help with the same ?

Thanks n Regards,
   Karthik R

**Comment by ThoreWietzke** [comment]
Ok, several things in your implementation are questionable.

1. You plainly used `convergence_test_gradient` and `convergence_test_constraints` but I don't see any implementation for these functions. 
2. you use `grampc_opt`/`grampc_sol` but you never defined these objects. They reference to the respective GRAMPC structures `opt` and `sol`, which are accessed by dot notation of the `Grampc` class.

First, you should make yourself familiar with the python interface of GRAMPC. I see that there is still a wide gap. 
Look at `src/pygrampc/_core.pyi` for all the fields exposed to python, as well as the functions.

**Comment by ThoreWietzke** [comment]
Some additional thought: GRAMPC itself can check if your OCP is converged, thus it is sufficient to set `MaxMultIter` to 100 and call just once `grampc.run()`. GRAMPC then solves the OCP for the time horizon `Thor`. You can plot the results, if you set `plot_prediction` to True.

**Comment by karthyyy** [comment]
Hi @ThoreWietzke,

  Thanks for the response. Please see the reply.

> 1) You plainly used convergence_test_gradient and convergence_test_constraints but I don't see any implementation for these functions
> 
> 2) you use grampc_opt/grampc_sol but you never defined these objects. They reference to the respective GRAMPC structures opt and sol, which are accessed by dot notation of the Grampc class.

Reply :- These were the functions used in GRAMPC. I assumed these are inherently defined and there will be equivalent functions in python. For eg, the functions are declared in "grampcrun.h" and  defined in "grampcrun.c" is as follows

```
/* test if gradient is converged ||u-uprev|| / ||u|| < rel_tol */
typeBoolean convergence_test_gradient(typeRNum rel_tol, const typeGRAMPC *grampc);

/* test if constraints are converged cfct[i] < abs_tol[i] */
typeBoolean convergence_test_constraints(ctypeRNum *abs_tol, const typeGRAMPC *grampc);
```

   Since I couldn't find any help files for python implementation, I was stuck there. As you pointed out in the previous response, I may not be using these functions further.

> 3) First, you should make yourself familiar with the python interface of GRAMPC. I see that there is still a wide gap.

Reply :- True. The coding process and structure of GRAMPC along with many examples are detailed in the manual coming with package which can be easily understood but I couldnt find equivalent in PYGRAMPC. If you can share any help files even its draft, it would be much appreciated. Meanwhile can you please clarify the following to help me understand better. Please correct the following if wrong.

3.a) Timing wise there are 4 parameters in the program viz `Tsim, Thor, dt and Nhor`. Regarding Tsim, If my problem is OCP with fixed final time, whether the only requirement of `Tsim `is greater than or equal to Thor. Can I always put `Tsim = Thor` for OCP with fixed final time ? How `Nhor `and `Thor/dt` are related

3.b) By defining `vec = mpc.GrampcResults(grampc, Tsim, plot_results=plot, plot_statistics=plot)`, a memory corresponding to the parameters of grampc problem will be initialized and executing `grampc.run()` populates it with actual values.

3.c) If `grampc.run()` executes one MPC step and updates values inside rws and sol, then why `vec.update(grampc, i)` is required.

3.d) For Crane2D example, `grampc.estim_penmin(True)` is executed but for Double Integrator its not present. Is it because Double Integrator problem is simple ? Whether values of those settings explicitly defined for Double Integrator in GRAMPC implementation is obtained from executing `grampc.estim_penmin(True)` earlier ?

   Other than this, the code for Double Integrator example for PYGRAMPC is straight forward.

> 4) Look at src/pygrampc/_core.pyi for all the fields exposed to python, as well as the functions.

Reply :- I just went through the same. Whether all features and functions in GRAMPC is available in PYGRAMPC or is it an abridged one (as I couldn't find `convergence_test_gradient `equivalent in python) ?

  I am able to implement this example (both OCP and MPC) using SciPy but I want to make use of the capabilities of GRAMPC with respect to speed and code generation. Once everything is fine with PYGRAMPC, I am planning to move to GRAMPC.
 
Thanks n Regards,
    Karthik R

**Comment by ThoreWietzke** [comment]
Hello Karthik,

my apologies, the python interface does not implement every function available in C. Looking at the mentioned stub file (`.pyi`) you see all functions and classes available from C. Sadly there is no better documentation right now, but we are working on it in the future.

3a.) Tsim is only used for an MPC. When solving an OCP, only `Thor`, `dt` and `Nhor` are important. `dt` is the sample time of your simulation, where the internal sample does not necessarily match. This is set via `Nhor` which resembles the number of discretization points, thus the internal sample is 
$\mathrm{dt}_{internal} = \frac{\mathrm{Thor}}{\mathrm{Nhor} - 1}$.
After finishing the computation, GRAMPC interpolates the next control in `grampc.sol.unext`.  So you should set your `Nhor` and `Thor` accordingly to your desired discretization.

3.b and c) `vec` is an easier interface, also used in the Matlab interface, to store the results of an MPC. Normally, no adjungate states are provided in `grampc.sol`, but for debugging reasons they are quite handy. They are only available in `grampc.rws`, which holds the scaled values used for computation. 
`vec` is never required, but it makes the implementation easier. For an OCP, it does not hold any additional value.

3.d) I would not say that. This function helps to set the penalty factor which is important for convergence of constrained optimization. Please look inside the GRAMPC manual for further information.

**Comment by karthyyy** [comment]
@ThoreWietzke ,

  Thanks for the response. I shall check the same and get back.

Regards
   Karthik

**Comment by karthyyy** [comment]
Hi @ThoreWietzke ,

  Thank you. 

> 1) Tsim is only used for an MPC. When solving an OCP, only Thor, dt and Nhor are important. 

Reply :- But for declaring vec, we need Tsim as `vec = mpc.GrampcResults(grampc, Tsim, plot_results=plot, plot_statistics=plot)`, ryt

> 2) dt is the sample time of your simulation, where the internal sample does not necessarily match. This is set via Nhor which resembles the number of discretization points, thus the internal sample is

Reply :- So if I make Nhor = Thor/dt, then both the simulation time and internal sampling time will be equal, ryt. In that case, whether interpolation will be executed ? I understand due to large number of points, simulation will be slow. Just to know the case.

3) As per your suggestions, I have set the options as given below. The, `'ConvergenceCheck' is "on".` So I removed the related functions in the python code.  Updated the parameters `"Thor"  :  5.25,  "dt"    :  0.01, and "Nhor": 50`. "Tmax" and "Tmin" are not relevant, ryt. Executed the following program.  

```
if __name__ == "__main__":
    plot = True    
    MaxMultSimIter = 100                                         # From C Code. Not present in original python
    Problem = DoubleIntegrator()
       
    grampc = mpc.Grampc(Problem, plot_prediction=False)

    grampc.set_param({"x0"    :  [-1.0, -1.0],
                      "xdes"  :  [0.0, 0.0],
                      "u0"    :  [0.0],
                      "udes"  :  [0.0],
                      "umax"  :  [1.0],
                      "umin"  :  [-1.0],
                      "Thor"  :  5.25,                          # From C Code. Original :- 6.0
                      "Tmax"  :  10.0,                          # From C Code. Original :- 20.0
                      "Tmin"  :  1.0,                           # From C Code. Original :- 0.001
                      "dt"    :  0.01,                          # From C Code. Original :- 0.001
                      "t0"    :  0.0
                    })

    grampc.set_opt({  "OptimTime": "off",                       # From C Code. Original :- on
                      "ShiftControl": "off",                    # From C Code. Not present in original
                      "Nhor": 50,                               # From C Code. Not present in original
                      "MaxGradIter": 200,                       # From C Code. Not present in original
                      "MaxMultIter": 1,                         # From C Code. Not present in original
                      "LineSearchMax": 1e2,                     # From C Code. Not present in original
                      "Integrator": "euler",                    # From C Code. Not present in original
                      "PenaltyMin": 1e1,                        # From C Code. Not present in original
                      "PenaltyIncreaseFactor": 1.25,            # From C Code. Not present in original
                      "PenaltyDecreaseFactor": 1.0,             # From C Code. Not present in original
                      "ConvergenceCheck": "on",                 # From C Code. Not present in original
                      "ConvergenceGradientRelTol": 1e-9,        # From C Code. Not present in original                      
                      "OptimTimeLineSearchFactor": 0.35,
                      "ConstraintsAbsTol": [1e-6, 1e-6, 1e-6]   # From C Code. Original :- [1e-3, 1e-3]
                   })

    Tsim = 5.0
    vec = mpc.GrampcResults(grampc, Tsim, plot_results=plot, plot_statistics=plot)  # Instead of Tsim, should I put Thor ?

    dt = grampc.param.dt

    for iOCP in range(0, MaxMultSimIter):

        vec.CPUtime[iOCP] = grampc.run()
        vec.update(grampc, iOCP)

        print("iOCP is ", iOCP)        


    vec.plot()
    plt.show()
```
  The output is simulated till 1 sec only as follows. With increase in MaxMultSimIter, the simulation time also extends but the states are constant. What may be the reason ?

![image](https://github.com/user-attachments/assets/6cea683e-8bea-4d1e-9ad0-3299d0a1e946)


Thanks n Regards,
   Karthik

**Comment by ThoreWietzke** [comment]
Hello Karthy,

what I was trying to say: you don't need `GrampcResults` when you are solving an OCP. Right now your code actually solves for 10000 Multiplier iterations, which is extremely high. You should remove the for loop. If you want to see the solution of GRAMPC, you should set

```python
grampc = mpc.Grampc(Problem, plot_prediction=True)
...
# set your parameters here
...
CPUtime = grampc.run()
print(f"CPU: {CPUtime}ms")
grampc.plot()
plt.show()
```
This calls `grampc.run()` once and plots the prediction or in your case, the solution of the OCP.

**Comment by karthyyy** [comment]
Hi @ThoreWietzke ,

  Thank you.

> 1) Right now your code actually solves for 10000 Multiplier iterations, which is extremely high. You should remove the for loop

I also thought about that. If thats the case, the what is the need for `for (iOCP = 0; iOCP <= MaxMultSimIter; iOCP++) {` loop in the `main_OCP_DOUBLE_INTEGRATOR.c `file ? The variable `MaxMultSimIter` is different from `MaxMultIter`.

2) If I change `Thor`, the value is updated and reflected in the waveforms and size of variables. But if I update `"xdes"  :  [1.0, 1.0], ` from `"xdes"  :  [0.0, 0.0],`, my final solved state value is still around [0, 0].

Regards
 Karthik

**Comment by ThoreWietzke** [comment]
Ok, now I see the misunderstanding. The c example for the OCP specifically set `MaxMultIter` to 1, so you can inspect the intermediate values of your states and controls for every multiplier step. Here you can for yourself do a convergence check, but GRAMPC also provides an option for that. 
In the end, if you do multiple calls of `grampc.run()` with `MaxMultIter` set to 1, like
```python
grampc.run()
grampc.run()
grampc.run()
```
you effectively do 3 multiplier iterations just like, if you set `MaxMultIter` to 3.

For your second point, did you added the states in your integral and/or terminal cost?

**Comment by karthyyy** [comment]
Hi @ThoreWietzke ,

  Thanks for the response.

1)  In c code, by setting `MaxMultIter=1` implies only 1 multiplier iteration will be executed but by setting `MaxMultSimIter =200` and `MaxMultIter=1`, maximum multiplier iterations can run upto 200 unless convergence occurs ?, Please correct if wrong.

2) Can you please clarify one fundamental doubt. Specifying the final values in `"xdes"  :  [0.5, 0.5],` doesn't make it a terminal constraint which needs to be satisfied ? 

Regards
   Karthik

**Comment by ThoreWietzke** [comment]
1. That's correct, because GRAMPC is run inside a for loop and the convergence is checked manually. 
2. Can you please share your problem formulation? (The class in Python) just write it here in a code block with three aposthrope at the start and at the end (you can also write the language after the first apostrophes, e.g. python)

**Comment by karthyyy** [comment]
Hi @ThoreWietzke ,

  This is my class. Here the final state values are given in the function `gTfct`. Whether `xdes`  is not passing to the function ? Do we need to give the terminal values manually. ? Also I put the desired values as a terminal constraint and not in the cost function. Its working.

```
class DoubleIntegrator(mpc.ProblemBase):
    def __init__(self):
        mpc.ProblemBase.__init__(self)
        self.Nx  = 2                # No of State variables
        self.Nu  = 1                # No of Control variables
        self.Np  = 0                # No of Parameters
        self.Ng  = 0                # No of State Equality constraints
        self.Nh  = 0                # No of State Inequality constraints
        self.NgT = 2                # No of Terminal equality constraints
        self.NhT = 0                # No of Terminal Inequality constraints

        self.CostIntegral = 0.1     # Integral cost weight
        self.CostTerminal = 1.0     # Terminal cost weight

    # System Dynamics - f
    def ffct(self, out, t, x, u, p):
        out[0] = x[1]
        out[1] = u[0]

    # (df/dx).T @ vec   <->   vec = [vec[0] vec[1]].T
    def dfdx_vec(self, out, t, x, vec, u, p):
        out[0] = 0
        out[1] = vec[0]

    # (df/du).T @ vec   <->   vec = [vec[0] vec[1]].T
    def dfdu_vec(self, out, t, x, vec, u, p):
        out[0] = vec[1]

    # Integral cost function - l
    def lfct(self, out, t, x, u, p, xdes, udes):
        out[0] = self.CostIntegral * (u[0] - udes[0]) ** 2

    # dau(l)/dau(u)
    def dldu(self, out, t, x, u, p, xdes, udes):
        out[0] = 2 * self.CostIntegral * (u[0] - udes[0])

    # Terminal cost function - V
    def Vfct(self, out, T, x, p, xdes):
        out[0] = self.CostTerminal * T

     # dau(V)/dau(T)
    def dVdT(self, out, T, x, p, xdes):
        out[0] = self.CostTerminal

    # Terminal Equality constraint
    def gTfct(self, out, T, x, p):
        out[0] = x[0] - 1.2
        out[1] = x[1] - 0.8

    # dau(gT)/dau(x).T @ vec
    def dgTdx_vec(self, out, T, x, p, vec):
        out[0] = vec[0]
        out[1] = vec[1]

    # InEquality constraint
    def hfct(self, out, T, x, p, xdes):
        out[0] = x[1] - 0.5             

    # dau(hT)/dau(x).T @ vec
    def dhdx_vec(self, out, T, x, u, p, vec):
        out[0] = 0         
        out[1] = vec[0] 
```

Thanks n Regards,
   Karthik R

**Comment by ThoreWietzke** [comment]
Thanks for your problem description. You are right, `xdes` is currently only passed in the cost functions. If you want to pass `xdes` to other functions, like gTfct, you have to create a field `self.xdes`  in the problem description. For Python it's best practice to do this in the `__init__` method.
In your specific case, you set your terminal equality constraints to x0=1.2 and x1=0.8, which are fixed right now.

A direct coupling to the `xdes` field is currently not possible, but will be addressed in the next GRAMPC release.

**Comment by karthyyy** [comment]
@ThoreWietzke,

   Thanks for the response. I believe things are sorted out now with the example. I shall dive into using PYGRAMPC for my problem and get back to you, incase any doubts are there. Thanks a lot for your support and prompt responses in clarifying the doubts. It meant a lot to us, those without much experience and guidance, to strive in the field of optimization.

Regards
   Karthik R

**Comment by karthyyy** [comment]
@ThoreWietzke,

   Thanks for the response. I believe things are sorted out now with the example. I shall dive into using PYGRAMPC for my problem and get back to you, incase any doubts are there. Thanks a lot for your support and prompt responses in clarifying the doubts. It meant a lot to us, those without much experience and guidance, to strive in the field of optimization.

Regards
   Karthik R
